apiVersion: v1 
kind: Pod 
metadata: 
    name: dind
    labels: {}
spec: 
    containers: 
      - name: docker-cmds
        image: vladpbr/images-portal-grpc-server:1.0
        ports:
        - containerPort: 7777             # grpc server
          protocol: TCP
        resources: 
            requests: 
                cpu: 10m 
                memory: 256Mi 
        env: 
        securityContext: 
            privileged: true              # docker-in-docker must run as a privileged container
        volumeMounts: 
          - name: docker-graph-storage    # empty placeholder directory for docker
            mountPath: /var/lib/docker
    volumes: 
      - name: docker-graph-storage        # empty placeholder directory for docker
        emptyDir: {}